puts ""
set lst [list "Fan" "Kristy" "Susan"]
puts "lindex"
puts "The first person is [lindex $lst 0]"
puts "The last person is [lindex $lst end]"
puts ""
puts "llength"
puts "The length of 'lst' is [llength $lst]"
puts ""
puts "lappend"
lappend lst "Peter"
puts "Updated: $lst"
puts ""
puts "linsert"
set newlst1 [linsert $lst 2 "Tom"]
puts "The new list 'newlst1': $newlst1"
puts ""
puts "lreplace"
set newlst2 [lreplace $lst 3 3 "Rachel"]
puts "The new list 'newlst2': $newlst2"
puts ""
puts "lreplace - replacing with nothing"
set newlst3 [lreplace $lst end end]
puts "The new list 'newlst3': $newlst3"
puts ""
puts "lsort"
set newlst4 [lsort -ascii $lst]
puts "The list in order: $newlst4"
puts ""
puts "lsearch"
puts "If found - Returns the position of the item in the list"
puts "Else - Returns -1"
puts "'Peter' is at [lsearch $lst "Peter"]-position in the list"
puts "'Charles' is at [lsearch $lst "Charles"]-position in the list"
puts ""
